// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi9vUaDNcJDq-kHXgcuSoPUfyzDhkrGKg',
    appId: '1:927063479128:web:ec24a6b3aa2561c8b1cb2d',
    messagingSenderId: '927063479128',
    projectId: 'fun2view-24d57',
    authDomain: 'fun2view-24d57.firebaseapp.com',
    storageBucket: 'fun2view-24d57.appspot.com',
    measurementId: 'G-3GQL8HS56N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPtma4HArWcz40XXkYvoP2wFhEdM61P8g',
    appId: '1:927063479128:android:42c7a8b4ebb6ddb6b1cb2d',
    messagingSenderId: '927063479128',
    projectId: 'fun2view-24d57',
    storageBucket: 'fun2view-24d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKvt5rpuZRv0H1OyP5LHmJav47MnZGOXU',
    appId: '1:927063479128:ios:aa8c274cd18c9bb5b1cb2d',
    messagingSenderId: '927063479128',
    projectId: 'fun2view-24d57',
    storageBucket: 'fun2view-24d57.appspot.com',
    iosClientId: '927063479128-ls3l5r0egj9ocpa4n65lib1jot1esa0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fun2viewAppli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKvt5rpuZRv0H1OyP5LHmJav47MnZGOXU',
    appId: '1:927063479128:ios:aa8c274cd18c9bb5b1cb2d',
    messagingSenderId: '927063479128',
    projectId: 'fun2view-24d57',
    storageBucket: 'fun2view-24d57.appspot.com',
    iosClientId: '927063479128-ls3l5r0egj9ocpa4n65lib1jot1esa0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fun2viewAppli',
  );
}
